production:
  server: "https://heroku-private-pub-6969.herokuapp.com/faye" 

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension. 

  secret_token: "181de65f72ed4f8cb8ff27d2f01d5ba1965efbe7524781a4b279649f1b836d16"
  signature_expiration: 3600 # one day
